version: '3.1'

services:
  db:
    image: mysql:9.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "Y!*zrkNQ8RZiyKrd8Zjj"
    ports:
     - "3306:3306"
    # (this is just an example, not intended to be a production configuration)
